In [1]:
from sklearn.model_selection import train_test_split
import pandas as pd

df = pd.read_csv('pokemon.csv')
X = df.drop('Speed', axis=1)
y = df['Speed']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training set size:", len(X_train))
print("Testing set size:", len(X_test))
df.head(5)

Training set size: 640
Testing set size: 160


#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [2]:
import pandas as pd
df = pd.DataFrame({
    'A': [1,2,3,4,5],
    'B': [2,3,5,7,11],
    'C': [3,4,6,8,10]
})
corr_matrix = df.corr()
print(corr_matrix)

          A         B         C
A  1.000000  0.972272  0.993884
B  0.972272  1.000000  0.985847
C  0.993884  0.985847  1.000000


In [27]:
#Example

from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"R2 Score: {r2}")

Mean Squared Error: 2900.1936284934804
R2 Score: 0.4526027629719196


In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Predicted Values:")
print(y_pred)

print("First 5 Predicted Values:")
print(y_pred[:5])

Predicted Values:
[139.5475584  179.51720835 134.03875572 291.41702925 123.78965872
  92.1723465  258.23238899 181.33732057  90.22411311 108.63375858
  94.13865744 168.43486358  53.5047888  206.63081659 100.12925869
 130.66657085 219.53071499 250.7803234  196.3688346  218.57511815
 207.35050182  88.48340941  70.43285917 188.95914235 154.8868162
 159.36170122 188.31263363 180.39094033  47.99046561 108.97453871
 174.77897633  86.36406656 132.95761215 184.53819483 173.83220911
 190.35858492 124.4156176  119.65110656 147.95168682  59.05405241
  71.62331856 107.68284704 165.45365458 155.00975931 171.04799096
  61.45761356  71.66672581 114.96732206  51.57975523 167.57599528
 152.52291955  62.95568515 103.49741722 109.20751489 175.64118426
 154.60296242  94.41704366 210.74209145 120.2566205   77.61585399
 187.93203995 206.49337474 140.63167076 105.59678023 130.70432536
 202.18534537 171.13039501 164.91423047 124.72472569 144.81030894
 181.99635452 199.41369642 234.21436188 145.95665512  79.86

In [6]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np

In [12]:
X = np.array([[1,2], [3,4], [5,6]])
scaler = StandardScaler()
X_std = scaler.fit_transform(X)
print("Standardized features:")
print(X_std)

scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)
print("Normalized fearures:")
print(X_norm)

Standardized features:
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
Normalized fearures:
[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [15]:
from sklearn.preprocessing import StandardScaler
import numpy as np

X = np.array([[1,2], [3,4], [5,6]])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Scaled features:")
print(X_scaled)

Scaled features:
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [21]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
import numpy as np

X = np.array([[1,2], [3,4], [5,6]])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

y = np.array(['cat', 'dog', 'cat', 'bird'])
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

print("Scaled features:")
print(X_scaled)
print("Encoded labels:")
print(y_encoded)

Scaled features:
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
Encoded labels:
[1 2 1 0]


In [26]:
from sklearn.model_selection import train_test_split
import numpy as np

X = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
y = np.array([0,0,1,1,1])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training features:")
print(X_train)
print("Training labels:")
print(y_train)
print("Testing features:")
print(X_test)
print("Testing labels:")
print(y_test)

Training features:
[[ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
Training labels:
[1 1 0 1]
Testing features:
[[3 4]]
Testing labels:
[0]


In [42]:
!pip install --upgrade scikit-learn

   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
   -- ------------------------------------- 0.8/10.7 MB 1.5 MB/s eta 0:00:07
   ------ --------------------------------- 1.8/10.7 MB 2.4 MB/s eta 0:00:04
   ---------- ----------------------------- 2.9/10.7 MB 2.9 MB/s eta 0:00:03
   -------------- ------------------------- 3.9/10.7 MB 3.4 MB/s eta 0:00:02
   ------------------- -------------------- 5.2/10.7 MB 3.8 MB/s eta 0:00:02
   ------------------------ --------------- 6.6/10.7 MB 4.1 MB/s eta 0:00:02
   ----------------------------- ---------- 7.9/10.7 MB 4.3 MB/s eta 0:00:01
   --------------------------------- ----

In [47]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
data = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'red', 'blue'],
    'size':['small', 'medium', 'large', 'small', 'medium']
})
le = LabelEncoder()
data['color_encoded'] = le.fit_transform(data['color'])
ohe = OneHotEncoder(sparse_output=False)
encoded_data = ohe.fit_transform(data[['size']])
encoded_df = pd.DataFrame(encoded_data, columns=ohe.get_feature_names_out(), index=data.index)
print("Label encoded data:")
print(data)
print("\nOne-hot encoded data:")
print(encoded_df)

Label encoded data:
   color    size  color_encoded
0    red   small              2
1   blue  medium              0
2  green   large              1
3    red   small              2
4   blue  medium              0

One-hot encoded data:
   size_large  size_medium  size_small
0         0.0          0.0         1.0
1         0.0          1.0         0.0
2         1.0          0.0         0.0
3         0.0          0.0         1.0
4         0.0          1.0         0.0
